export const server = "https://udmailapp.web.app"
//export const server = "http://localhost:8080"
export const create_ud_account_path = "/create-ud-account"
export const sendmessage_path = "/sendmessage"
export const getemails_path = "/getemails"
export const getemail_path = "/getemail"